version: '3'
services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        HOST_UID: ${HOST_UID:?please run via bin/docker-compose}
    environment:
      - RACK_ENV
      - PLUM_PORT
      - PLUM_DATABASE_URL
      - PLUM_SESSION_KEY
    working_dir: /plum
    volumes:
      - ./app:/plum
      - ./bundle/${RACK_ENV}:/plum/vendor/bundle
    ports:
      - ${PLUM_PORT}:${PLUM_PORT}
    depends_on:
      - postgres
  postgres:
    image: "postgres:12-alpine"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
