source 'https://rubygems.org'

gem 'rake', '~> 13.0'
gem 'roda', '~> 3.34'
gem 'sequel', '~> 5.34'
gem 'sequel_pg', '~> 1.13'
gem 'rack', '~> 2.2'
gem 'rack-test', '~> 1.1'
gem 'rack-ssl-enforcer', '~> 0.2'
gem 'rack-jwt', git: 'https://github.com/maeveynot/rack-jwt', branch: 'exclude-regexp'
gem 'rack-unreloader', '~> 1.7'
gem 'refrigerator', '~> 1.2'

group :development do
  gem 'sequel-annotate', '~> 1.5'
end

group :test do
  gem 'minitest', '~> 5.14'
  gem 'minitest-hooks', '~> 1.5'
  gem 'warning', '~> 1.1'
end
